version: "3.8"
services:
 web:
  image: dimithur/bgapp-web
  deploy:
   replicas: 5
  ports:
   - 8080:80
  volumes:
   - "/home/vagrant/bgapp/web:/usr/share/nginx/html:ro"
  networks:
   - app-network
 db:
  image: dimithur/bgapp-db
  networks:
   - app-network
  environment:
   MYSQL_ROOT_PASSWORD: "12345"
networks:
 app-network:
